### ISSUE TITLE
Reading previous selection and current selection when filling in the blank

### ISSUE THREAD

**Issue by csoutter** [mikedoucettejr/Singable#2]
When you open this, if you select an option with the spacebar to read it out loud and then go to the next and do the same, it reads off first the previous option and then the currently highlighted option. For example, when I first open this, I have the option to pick a rabbit or dog. When I tab to dog first and click the spacebar, it says "I have a blank dog". Then if I tab to the rabbit and click space, it says "I have a dog rabbit". So on and so forth.

**Comment by nlaurenr** [comment]
Thank you for this feedback! I used the spacebar for all auditory controls, so I can refactor my event handler and use different keys for reading different elements. Hopefully that will fix this!

**Comment by nlaurenr** [comment]
I changed the event handlers so everything has its own key. I also added a preventDefault() to the spacebar handler, which was causing it to read the current lyric as well as the highlighted option!
