### ISSUE TITLE
Can't tab to your score

### ISSUE THREAD

**Issue by csoutter** [mikedoucettejr/Singable#3]
On the final page, you can't tab to your score. It'd be nice if that was announced as people went through the final page!

**Comment by nlaurenr** [comment]
Do you mean that I should make my score a button that will announce the score when clicked? Currently the space bar reads the last page, but I can see how that isn't perfectly intuitive, and the  instructions don't mention to do that.

**Comment by nlaurenr** [comment]
I added a button on the score so it can be read when clicked! I'll also add clearer instructions too :) thanks again Cassidy!
