### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by alvinayeung** [mikedoucettejr/Singable#4]
This is such a great idea! 
There are some things that I didn't understand how it worked: 
(1) I would suggest adding different keyboard clicks to different functions. For instance one key for reading the lyrics and pictures and another key for the 'next' button
(2) Also what is the singable score? I would write that in your front page because I was a little confused on its importance
Overall, great job!

**Comment by nlaurenr** [comment]
Thank you for this feedback! I think you're totally right on both counts. I'll make those fixes!
